name: Build Electron

on:
  push:
    branches: [development] 
  pull_request:
    branches: [development] 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x' 
      - name: Install Dependencies
        run: |
          cd apps/client/electron
          npm install
      - name: Build Electron
        run: |
          cd apps/client/electron
          npm run electron:pack 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
